name: FlowerBloom
author: MooseOnTehLoose
main: net.moosecraft.FlowerBloom.FlowerBloom
version: 2.0-1.20.4
api-version: 1.20
commands:
   flowerbloom:
      description: enable growing flowers with bonemeal
      usage: "instructions: https://github.com/MooseOnTehLoose/GlowTree"